# mysql Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysqltcp
      protocol: TCP
      targetPort: 3306
      port: 3306
      nodePort: 3306
# TargetPort: Container Port
# Port: Externer Port
